from django.urls import path
from . import views, reports

urlpatterns = [
    path('pessoal_setores',views.setores,name='pessoal_setores'),
    path('pessoal_setor_add',views.setor_add,name='pessoal_setor_add'),
    path('pessoal_setor_id/<int:id>',views.setor_id,name='pessoal_setor_id'),
    path('pessoal_setor_update/<int:id>',views.setor_update,name='pessoal_setor_update'),
    path('pessoal_setor_delete/<int:id>/delete',views.setor_delete,name='pessoal_setor_delete'),
    path('pessoal_cargos',views.cargos,name='pessoal_cargos'),
    path('pessoal_cargo_add',views.cargo_add,name='pessoal_cargo_add'),
    path('pessoal_cargo_id/<int:id>',views.cargo_id,name='pessoal_cargo_id'),
    path('pessoal_cargo_update/<int:id>',views.cargo_update,name='pessoal_cargo_update'),
    path('pessoal_cargo_delete/<int:id>/delete',views.cargo_delete,name='pessoal_cargo_delete'),
    path('pessoal_funcionarios',views.funcionarios,name='pessoal_funcionarios'),
    path('pessoal_funcionario_add',views.funcionario_add,name='pessoal_funcionario_add'),
    path('pessoal_funcionario_id/<int:id>',views.funcionario_id,name='pessoal_funcionario_id'),
    path('pessoal_funcionario_update/<int:id>',views.funcionario_update,name='pessoal_funcionario_update'),
    path('pessoal_funcionario_delete/<int:id>/delete',views.funcionario_delete,name='pessoal_funcionario_delete'),
    path('pessoal_funcionario_afastar',views.funcionario_afastar,name='pessoal_funcionario_afastar'),
    path('pessoal_funcionario_desligar',views.funcionario_desligar,name='pessoal_funcionario_desligar'),
    path('pessoal_afastamentos/<int:id>',views.afastamentos,name='pessoal_afastamentos'),
    path('pessoal_afastamento_add/<int:id>',views.afastamento_add,name='pessoal_afastamento_add'),
    path('pessoal_afastamento_id/<int:id>',views.afastamento_id,name='pessoal_afastamento_id'),
    path('pessoal_afastamento_update/<int:id>',views.afastamento_update,name='pessoal_afastamento_update'),
    path('pessoal_afastamento_delete/<int:id>/delete',views.afastamento_delete,name='pessoal_afastamento_delete'),
    path('pessoal_dependentes/<int:id>',views.dependentes,name='pessoal_dependentes'),
    path('pessoal_dependente_add/<int:id>',views.dependente_add,name='pessoal_dependente_add'),
    path('pessoal_dependente_id/<int:id>',views.dependente_id,name='pessoal_dependente_id'),
    path('pessoal_dependente_update/<int:id>',views.dependente_update,name='pessoal_dependente_update'),
    path('pessoal_dependente_delete/<int:id>/delete',views.dependente_delete,name='pessoal_dependente_delete'),
    path('pessoal_funcoes_fixas',views.funcoes_fixas,name='pessoal_funcoes_fixas'),
    path('pessoal_funcao_fixa_add',views.funcao_fixa_add,name='pessoal_funcao_fixa_add'),
    path('pessoal_funcao_fixa_id/<int:id>',views.funcao_fixa_id,name='pessoal_funcao_fixa_id'),
    path('pessoal_funcao_fixa_update/<int:id>',views.funcao_fixa_update,name='pessoal_funcao_fixa_update'),
    path('pessoal_funcao_fixa_delete/<int:id>/delete',views.funcao_fixa_delete,name='pessoal_funcao_fixa_delete'),
    path('pessoal_eventos',views.eventos,name='pessoal_eventos'),
    path('pessoal_evento_add',views.evento_add,name='pessoal_evento_add'),
    path('pessoal_evento_id/<int:id>',views.evento_id,name='pessoal_evento_id'),
    path('pessoal_evento_update/<int:id>',views.evento_update,name='pessoal_evento_update'),
    path('pessoal_evento_delete/<int:id>/delete',views.evento_delete,name='pessoal_evento_delete'),
    path('pessoal_get_setores',views.get_setores,name='pessoal_get_setores'),
    path('pessoal_get_funcionario',views.get_funcionario,name='pessoal_get_funcionario'),
    path('pessoal_get_funcionarios',views.get_funcionarios,name='pessoal_get_funcionarios'),
    path('pessoal_get_cargos',views.get_cargos,name='pessoal_get_cargos'),
    path('pessoal_get_cargos_ff',views.get_cargos_ff,name='pessoal_get_cargos_ff'),
    path('pessoal_export_funcionario_csv/<int:id>',reports.export_funcionario_csv,name='pessoal_export_funcionario_csv'),
]