# Generated by Django 5.1 on 2024-08-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selecao',
            name='detalhes',
            field=models.TextField(blank=True),
        ),
    ]
