# Generated by Django 4.0 on 2022-01-12 22:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
