# Generated by Django 3.2.3 on 2022-01-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selecao',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
