# Generated by Django 4.1.2 on 2023-04-19 14:44

import core.models
import core.validators
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=255)),
                ('historico', models.TextField(blank=True)),
                ('entrada', models.DateTimeField(default=datetime.datetime.now)),
                ('ultima_interacao', models.DateTimeField(default=datetime.datetime.now)),
                ('tipo', models.CharField(blank=True, choices=[('D', 'Duvida'), ('F', 'Falha'), ('M', 'Melhoria'), ('S', 'Sugestao')], max_length=3)),
                ('status', models.CharField(blank=True, choices=[('E', 'Em Espera'), ('A', 'Em Atendimento'), ('S', 'Aguardando Solicitante'), ('V', 'Pendente Validacao'), ('F', 'Fechado'), ('D', 'Em Desenvolvimento')], max_length=3)),
                ('classificacao', models.CharField(blank=True, choices=[('bug', 'Crash'), ('logc', 'Logic'), ('perm', 'Permission'), ('ench', 'Enhancement'), ('unpr', 'Unproven')], max_length=5)),
                ('avaliacao', models.PositiveIntegerField(blank=True, null=True)),
                ('analista', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='analista', to=settings.AUTH_USER_MODEL)),
                ('followers', models.ManyToManyField(blank=True, related_name='issue_followers', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('eh_suporte', 'Atuar como suporte')],
            },
        ),
        migrations.CreateModel(
            name='Issuefile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', core.models.FileField(blank=True, upload_to='core/issue/%Y/%m/%d', validators=[core.validators.validate_file_extension])),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.issue')),
            ],
        ),
    ]
