# Generated by Django 4.0.2 on 2022-03-11 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('console', 'Pode abrir o console'), ('docs', 'Acessar documentacao do sistema')]},
        ),
    ]
