# Generated by Django 4.1.1 on 2023-02-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='participantes',
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
