# Generated by Django 4.1.1 on 2023-04-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gera_notificacao_issue_atualizado', models.BooleanField(default=True)),
                ('quantidade_caracteres_senha', models.PositiveIntegerField(default=8)),
                ('senha_exige_alpha', models.BooleanField(default=True)),
                ('senha_exige_numero', models.BooleanField(default=True)),
                ('senha_exige_caractere', models.BooleanField(default=False)),
                ('historico_senhas_nao_repetir', models.PositiveIntegerField(default=8)),
                ('bloqueia_conta_por_tentativas_erradas', models.BooleanField(default=False)),
                ('quantidade_tentantivas_erradas', models.PositiveIntegerField(default=3)),
                ('valida_senha_comum', models.BooleanField(default=False)),
            ],
            options={
                'default_permissions': ('view', 'change'),
            },
        ),
    ]
