# Generated by Django 4.0 on 2021-12-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='empresas',
            field=models.ManyToManyField(to='core.Empresa'),
        ),
    ]
