# Generated by Django 4.1.2 on 2023-04-17 20:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appthread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(blank=True, max_length=70)),
                ('inicio', models.DateTimeField(default=datetime.datetime.now)),
                ('termino', models.DateTimeField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('detalhe', models.TextField(blank=True)),
                ('private', models.BooleanField(default=True)),
                ('validade', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
