# Generated by Django 4.1.2 on 2023-04-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='footer',
            field=models.TextField(blank=True),
        ),
    ]
