# Generated by Django 4.0 on 2021-12-14 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='alerta_de_sistema',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='from_user', to='auth.user'),
        ),
    ]
