# Generated by Django 4.0 on 2021-12-18 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('doc_maker', 'Pode criar documentacao')]},
        ),
    ]
