# Generated by Django 4.1.1 on 2023-02-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='config',
            field=models.TextField(blank=True),
        ),
    ]
