# Generated by Django 4.1.1 on 2023-02-12 07:06

import core.models
import core.validators
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_profile_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.date.today)),
                ('inicio', models.TimeField(blank=True, null=True)),
                ('termino', models.TimeField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=50)),
                ('detalhe', models.TextField(blank=True)),
                ('local', models.CharField(blank=True, max_length=220)),
                ('tags', models.CharField(blank=True, max_length=220)),
                ('anexo', core.models.FileField(blank=True, upload_to='core/agenda/anexos/%Y/%m/%d', validators=[core.validators.validate_excluded_files])),
                ('cancelado', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('create_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
