# Generated by Django 4.1.2 on 2023-04-19 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_issue_issuefile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuefile',
            options={'default_permissions': []},
        ),
        migrations.AlterField(
            model_name='issue',
            name='analista',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='analista', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='classificacao',
            field=models.CharField(blank=True, choices=[('', '---'), ('bug', 'Crash'), ('logc', 'Logic'), ('perm', 'Permission'), ('ench', 'Enhancement'), ('unpr', 'Unproven')], max_length=5),
        ),
        migrations.AlterField(
            model_name='issue',
            name='usuario',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
