# Generated by Django 3.2.3 on 2022-04-01 12:31

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empresa_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=core.models.ImageField(blank=True, upload_to='core/logos/'),
        ),
    ]
