# Generated by Django 3.2.3 on 2022-06-02 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'default_permissions': [], 'permissions': [('console', 'Pode abrir o console'), ('debug', 'DEBUG System'), ('docs', 'Acessar documentacao do sistema')]},
        ),
    ]
