# Generated by Django 4.0.2 on 2022-05-28 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trafego', '0001_initial'),
        ('oficina', '0001_initial'),
        ('globus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escala',
            name='linha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='trafego.linha'),
        ),
        migrations.AddField(
            model_name='escala',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oficina.frota'),
        ),
    ]
