# Generated by Django 4.0.2 on 2022-03-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='sentido',
            field=models.CharField(blank=True, choices=[('', '-----'), ('I', 'Ida'), ('V', 'Volta')], default='', max_length=3),
        ),
    ]
