# Generated by Django 4.0.2 on 2022-03-10 19:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('globus', '0003_escala_log_importacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='log_importacao',
            field=models.CharField(blank=True, default=datetime.datetime(2022, 3, 10, 15, 47, 5, 594438), max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consulta_escala_inicio', models.DateField(blank=True, default=None, null=True)),
                ('consulta_escala_fim', models.DateField(blank=True, default=None, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.empresa')),
            ],
        ),
    ]
