# Generated by Django 4.0.2 on 2022-03-11 00:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globus', '0004_alter_escala_log_importacao_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escala',
            options={'permissions': [('consultar_escala', 'Consultar escala pessoal'), ('localizar_escala', 'Consultar outras escalas'), ('importar_escala', 'Pode importar escala')]},
        ),
        migrations.AlterField(
            model_name='escala',
            name='log_importacao',
            field=models.CharField(blank=True, default=datetime.datetime(2022, 3, 10, 20, 54, 46, 679441), max_length=50, null=True),
        ),
    ]
