# Generated by Django 4.0.2 on 2022-03-11 01:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globus', '0005_alter_escala_options_alter_escala_log_importacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='log_importacao',
            field=models.CharField(blank=True, default=datetime.datetime(2022, 3, 10, 21, 6, 18, 625262), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='escala',
            name='status',
            field=models.CharField(blank=True, choices=[('E', 'Escalado'), ('F', 'Folga'), ('C', 'Compensacao'), ('R', 'Ferias'), ('P', 'Plantao'), ('A', 'Fora de Escala')], default='E', max_length=3),
        ),
    ]
