# Generated by Django 4.1.2 on 2023-07-26 18:23

import core.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True)),
                ('css_breakpoint', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'default_permissions': ('add', 'change', 'delete'),
            },
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('empresa', models.CharField(blank=True, max_length=100)),
                ('rg', models.CharField(blank=True, max_length=20)),
                ('cpf', models.CharField(blank=True, max_length=20)),
                ('fone1', models.CharField(blank=True, max_length=20)),
                ('fone2', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=150)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=60)),
                ('uf', models.CharField(blank=True, max_length=5)),
                ('foto', core.models.ImageField(blank=True, upload_to='portaria/fotos/')),
                ('detalhe', models.TextField(blank=True)),
                ('bloqueado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=20)),
                ('cor', models.CharField(blank=True, max_length=15)),
                ('placa', models.CharField(max_length=15)),
                ('valido_ate', models.DateField(blank=True, default=datetime.datetime.today, null=True)),
                ('km_inicial', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='pessoal.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('fixa', models.BooleanField(default=False)),
                ('ocupada', models.BooleanField(default=False)),
                ('inativa', models.BooleanField(default=True)),
                ('detalhe', models.CharField(blank=True, max_length=100)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='portaria.area')),
            ],
            options={
                'permissions': [('view_registro', 'Visualizar registro'), ('add_registro', 'Adicionar registro'), ('update_registro', 'Atualizar registro'), ('delete_registro', 'Excluir registro')],
            },
        ),
        migrations.CreateModel(
            name='RegistroVisitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField(default=datetime.datetime.today)),
                ('hora_entrada', models.TimeField(default=datetime.datetime.now)),
                ('km_entrada', models.PositiveIntegerField(blank=True, null=True)),
                ('data_saida', models.DateField(blank=True, null=True)),
                ('hora_saida', models.TimeField(blank=True, null=True)),
                ('km_saida', models.PositiveIntegerField(blank=True, null=True)),
                ('detalhe', models.CharField(blank=True, max_length=200)),
                ('modelo', models.CharField(blank=True, max_length=20)),
                ('cor', models.CharField(blank=True, max_length=15)),
                ('placa', models.CharField(blank=True, max_length=15)),
                ('autorizado_por', models.CharField(blank=True, max_length=80)),
                ('vaga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='portaria.vaga')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='portaria.visitante')),
            ],
            options={
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='RegistroFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField(default=datetime.datetime.today)),
                ('hora_entrada', models.TimeField(default=datetime.datetime.now)),
                ('km_entrada', models.PositiveIntegerField(blank=True, null=True)),
                ('data_saida', models.DateField(blank=True, null=True)),
                ('hora_saida', models.TimeField(blank=True, null=True)),
                ('km_saida', models.PositiveIntegerField(blank=True, null=True)),
                ('detalhe', models.CharField(blank=True, max_length=200)),
                ('vaga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='portaria.vaga')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='portaria.veiculo')),
            ],
            options={
                'default_permissions': [],
            },
        ),
    ]
