# Generated by Django 4.1.2 on 2023-07-21 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'default_permissions': ('add', 'update', 'delete')},
        ),
    ]
