# Generated by Django 4.1.2 on 2023-08-01 13:52

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitante',
            name='foto',
            field=core.models.ImageField(blank=True, upload_to='portaria/visitante/'),
        ),
    ]
