# Generated by Django 4.1.2 on 2023-08-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitante',
            name='cpf',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
