# Generated by Django 4.1.2 on 2023-07-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0002_alter_area_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='detalhe',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
