# Generated by Django 4.1.2 on 2023-08-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0002_alter_visitante_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
