# Generated by Django 4.1.2 on 2023-07-26 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0003_vaga_detalhe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'default_permissions': ('add', 'change', 'delete')},
        ),
        migrations.AddField(
            model_name='registrofuncionario',
            name='vaga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='portaria.vaga'),
        ),
    ]
