# Generated by Django 4.2.4 on 2023-08-24 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0005_alter_registrofuncionario_veiculo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaga',
            options={'permissions': [('view_registro', 'Visualizar registro'), ('add_registro', 'Adicionar registro'), ('delete_registro', 'Excluir registro')]},
        ),
    ]
