# Generated by Django 4.1.2 on 2023-05-12 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('arquivo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limite',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.empresa', unique=True),
        ),
    ]
