# Generated by Django 4.1.2 on 2023-05-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='limite',
            name='armazenamento',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
