# Generated by Django 4.1.2 on 2023-05-17 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arquivo', '0003_alter_limite_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ativo',
            name='historico',
        ),
    ]
