# Generated by Django 4.1.2 on 2023-05-17 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arquivo', '0004_remove_ativo_historico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ativo',
            options={'permissions': [('descartar_ativo', 'Pode descartar')]},
        ),
    ]
