# Generated by Django 3.2.3 on 2022-06-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sac', '0002_alter_reclamacao_parecer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamacao',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
