from django.urls import path
from . import views

urlpatterns = [
    path('oficina_frotas',views.frotas,name='oficina_frotas'),
    path('oficina_frota_add',views.frota_add,name='oficina_frota_add'),
    path('oficina_frota_id/<int:id>',views.frota_id,name='oficina_frota_id'),
    path('oficina_frota_update/<int:id>',views.frota_update,name='oficina_frota_update'),
    path('oficina_frota_delete/<int:id>/delete',views.frota_delete,name='oficina_frota_delete'),
    path('oficina_marcas',views.marcas,name='oficina_marcas'),
    path('oficina_marca_add',views.marca_add,name='oficina_marca_add'),
    path('oficina_marca_id/<int:id>',views.marca_id,name='oficina_marca_id'),
    path('oficina_marca_update/<int:id>',views.marca_update,name='oficina_marca_update'),
    path('oficina_marca_delete/<int:id>/delete',views.marca_delete,name='oficina_marca_delete'),
    path('oficina_classificacoes',views.classificacoes,name='oficina_classificacoes'),
    path('oficina_classificacao_add',views.classificacao_add,name='oficina_classificacao_add'),
    path('oficina_classificacao_id/<int:id>',views.classificacao_id,name='oficina_classificacao_id'),
    path('oficina_classificacao_update/<int:id>',views.classificacao_update,name='oficina_classificacao_update'),
    path('oficina_classificacao_delete/<int:id>/delete',views.classificacao_delete,name='oficina_classificacao_delete'),
    path('oficina_categorias',views.categorias,name='oficina_categorias'),
    path('oficina_categoria_add',views.categoria_add,name='oficina_categoria_add'),
    path('oficina_categoria_id/<int:id>',views.categoria_id,name='oficina_categoria_id'),
    path('oficina_categoria_update/<int:id>',views.categoria_update,name='oficina_categoria_update'),
    path('oficina_categoria_delete/<int:id>/delete',views.categoria_delete,name='oficina_categoria_delete'),
    path('oficina_componentes',views.componentes,name='oficina_componentes'),
    path('oficina_componente_add',views.componente_add,name='oficina_componente_add'),
    path('oficina_componente_id/<int:id>',views.componente_id,name='oficina_componente_id'),
    path('oficina_componente_update/<int:id>',views.componente_update,name='oficina_componente_update'),
    path('oficina_componente_delete/<int:id>/delete',views.componente_delete,name='oficina_componente_delete'),
    path('oficina_carrocerias',views.carrocerias,name='oficina_carrocerias'),
    path('oficina_carroceria_add',views.carroceria_add,name='oficina_carroceria_add'),
    path('oficina_carroceria_id/<int:id>',views.carroceria_id,name='oficina_carroceria_id'),
    path('oficina_carroceria_update/<int:id>',views.carroceria_update,name='oficina_carroceria_update'),
    path('oficina_carroceria_delete/<int:id>/delete',views.carroceria_delete,name='oficina_carroceria_delete'),
    path('oficina_modelos',views.modelos,name='oficina_modelos'),
    path('oficina_modelo_add',views.modelo_add,name='oficina_modelo_add'),
    path('oficina_modelo_id/<int:id>',views.modelo_id,name='oficina_modelo_id'),
    path('oficina_modelo_update/<int:id>',views.modelo_update,name='oficina_modelo_update'),
    path('oficina_modelo_delete/<int:id>/delete',views.modelo_delete,name='oficina_modelo_delete'),
    path('oficina_get_frota_placa',views.get_frota_placa,name='oficina_get_frota_placa'),
    path('oficina_get_frota_empresa',views.get_frota_empresa,name='oficina_get_frota_empresa'),
    path('oficina_get_frota',views.get_frota,name='oficina_get_frota'),
    path('oficina_get_marcas',views.get_marcas,name='oficina_get_marcas'),
    path('oficina_get_modelos',views.get_modelos,name='oficina_get_modelos'),
    path('oficina_get_componentes',views.get_componentes,name='oficina_get_componentes'),
    path('oficina_get_categorias',views.get_categorias,name='oficina_get_categorias'),
    path('oficina_get_classificacoes',views.get_classificacoes,name='oficina_get_classificacoes'),
]