# Generated by Django 3.2.3 on 2022-02-04 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frota',
            options={'permissions': [('alterar_prefixo', 'Pode alterar prefixo'), ('vender_frota', 'Pode vender frota'), ('movimentar_em_massa', 'Pode movimentar em massa'), ('dashboard_frota', 'Pode usar o dashboard frota')]},
        ),
    ]
