# Generated by Django 3.2.3 on 2022-01-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frota',
            name='componentes',
            field=models.ManyToManyField(related_name='frota_componentes', to='oficina.Componente'),
        ),
    ]
