# Generated by Django 3.2.3 on 2022-01-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0002_alter_frota_componentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='frota',
            name='aniversario',
            field=models.DateField(blank=True, null=True),
        ),
    ]
