# Generated by Django 4.0.2 on 2022-02-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafego', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planejamento',
            name='status',
        ),
        migrations.AddField(
            model_name='planejamento',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
    ]
