# Generated by Django 3.2.3 on 2022-02-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafego', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linha',
            name='detalhe',
            field=models.TextField(blank=True),
        ),
    ]
