# Generated by Django 3.2.3 on 2022-05-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafego', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predefinido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=80)),
                ('detalhe', models.TextField(blank=True)),
            ],
        ),
    ]
