# Generated by Django 4.0 on 2022-02-06 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trafego', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ocorrencia',
            options={'permissions': [('dashboard_ocorrencia', 'Pode ver dashboard ocorrencia'), ('tratar_ocorrencia', 'Pode tratar ocorrencia')]},
        ),
    ]
