# Generated by Django 3.2.3 on 2022-02-04 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trafego', '0002_linha_detalhe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linha',
            options={'permissions': [('dop_linha', 'Pode acessar DOP')]},
        ),
    ]
