# Generated by Django 4.0.2 on 2022-02-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafego', '0002_remove_planejamento_status_planejamento_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='planejamento',
            name='patamares',
            field=models.TextField(blank=True),
        ),
    ]
