# Generated by Django 4.0.5 on 2022-07-08 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trafego', '0002_alter_trajeto_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trajeto',
            name='tipo',
        ),
    ]
