# Generated by Django 3.2.3 on 2022-02-04 18:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import trafego.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oficina', '0002_alter_frota_options'),
        ('core', '0002_alter_empresa_options'),
        ('pessoal', '0002_alter_funcionario_options'),
        ('trafego', '0003_alter_linha_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Providencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='localidade',
            name='ponto_de_controle',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, default=datetime.datetime.today, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('indisciplina_condutor', models.BooleanField(default=False)),
                ('gravidade', models.CharField(blank=True, choices=[('L', 'Leve'), ('M', 'Medio'), ('G', 'Grave')], default='L', max_length=2)),
                ('viagem_omitida', models.BooleanField(default=False)),
                ('tratado', models.BooleanField(default=False)),
                ('detalhe', models.TextField(blank=True)),
                ('condutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='pessoal.funcionario')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.empresa')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='trafego.evento')),
                ('linha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='trafego.linha')),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='trafego.localidade')),
                ('providencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='trafego.providencia')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='oficina.frota')),
            ],
            options={
                'permissions': [('tratar_ocorrencia', 'Pode tratar ocorrencia')],
            },
        ),
        migrations.CreateModel(
            name='FotoOcorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='trafego/%Y/%m/%d', validators=[trafego.validators.validate_file_extension])),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trafego.ocorrencia')),
            ],
        ),
    ]
