# Generated by Django 3.2.3 on 2022-02-04 19:31

import core.models
from django.db import migrations
import trafego.validators


class Migration(migrations.Migration):

    dependencies = [
        ('trafego', '0005_alter_fotoocorrencia_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoocorrencia',
            name='foto',
            field=core.models.ImageField(upload_to='trafego/ocorrencias/%Y/%m/%d', validators=[trafego.validators.validate_file_extension]),
        ),
    ]
