# Generated by Django 3.2.3 on 2022-02-10 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acidente',
            options={'permissions': [('tratar_acidente', 'Tratar acidentes de outros inspetores'), ('dashboard_acidente', 'Pode acessar dashboard acidentes')]},
        ),
    ]
