# Generated by Django 3.2.3 on 2022-03-21 11:54

import core.models
from django.db import migrations, models
import django.db.models.deletion
import sinistro.validators


class Migration(migrations.Migration):

    dependencies = [
        ('sinistro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', core.models.FileField(blank=True, upload_to='sinistro/files/%Y/%m/%d', validators=[sinistro.validators.validate_excluded_files])),
                ('acidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sinistro.acidente')),
            ],
        ),
    ]
