# Generated by Django 4.0 on 2022-02-13 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistro', '0002_alter_acidente_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terceiro',
            old_name='sinistro',
            new_name='acidente',
        ),
    ]
