# Generated by Django 3.2.3 on 2022-04-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analytics_foco_mes_atual', models.BooleanField(default=True)),
            ],
            options={
                'default_permissions': [('view', 'change')],
            },
        ),
    ]
