# Generated by Django 4.1.2 on 2023-02-01 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diretriz',
            options={'default_permissions': [], 'permissions': [('dashboard', 'Pode ver dashboard'), ('staff', 'Gerir a Staff'), ('view_kanban', 'Visualizar Kanban'), ('change_kanban', 'Editar Kanban')]},
        ),
    ]
