# Generated by Django 3.2.3 on 2022-04-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicador',
            name='evolucao',
        ),
        migrations.AddField(
            model_name='apontamento',
            name='evolucao',
            field=models.IntegerField(blank=True, choices=[(1, 'Melhorou'), (0, 'Manteve'), (-1, 'Piorou')], null=True),
        ),
    ]
