# Generated by Django 3.2.3 on 2022-04-08 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diretriz',
            options={'default_permissions': [], 'permissions': [('dashboard', 'Pode ver dashboard'), ('staff', 'Gerir a Staff')]},
        ),
    ]
