# Generated by Django 4.1.2 on 2023-05-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='gerar_alerta_nova_analise',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='gerar_alerta_nova_diretriz',
            field=models.BooleanField(default=True),
        ),
    ]
