# Generated by Django 4.1.1 on 2023-02-04 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='inicio',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
