# Generated by Django 4.0.2 on 2022-04-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='staff',
            field=models.ManyToManyField(to='gestao.Staff'),
        ),
    ]
