# Generated by Django 3.2.3 on 2022-05-31 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='precisao',
            field=models.IntegerField(default=2),
        ),
    ]
