# Generated by Django 3.2.3 on 2022-04-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='medida',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
