# Generated by Django 4.0.2 on 2022-04-09 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_indicador_medida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicador',
            options={'default_permissions': ['add']},
        ),
    ]
