# Generated by Django 4.0.2 on 2022-04-09 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_alter_indicador_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apontamento',
            options={'default_permissions': ['add']},
        ),
        migrations.AlterModelOptions(
            name='indicador',
            options={'default_permissions': []},
        ),
    ]
