# Generated by Django 4.0.2 on 2022-04-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_alter_apontamento_options_alter_indicador_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='bloqueado',
            field=models.BooleanField(default=False),
        ),
    ]
