# Generated by Django 4.0.2 on 2022-04-03 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_alter_plano_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plano_responsavel', to='gestao.staff'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='plano_staff', to='gestao.Staff'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('M', 'Manager'), ('E', 'Extrategico'), ('G', 'Gerencial'), ('O', 'Operacional')], default='O', max_length=3),
        ),
    ]
