# Generated by Django 4.0.2 on 2022-04-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0005_plano_bloqueado'),
    ]

    operations = [
        migrations.AddField(
            model_name='analise',
            name='tipo',
            field=models.CharField(choices=[('L', 'Lembrete'), ('M', 'Melhoria'), ('N', 'Nao Conformidade')], default='L', max_length=3),
        ),
    ]
