# Generated by Django 3.2.3 on 2022-02-04 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'permissions': [('associar_usuario', 'Pode associar usuario a funcionário'), ('afastar_funcionario', 'Pode afastar funcionário'), ('desligar_funcionario', 'Pode desligar funcionário'), ('dashboard_funcionario', 'Pode acessar dashboard pessoal')]},
        ),
    ]
