# Generated by Django 4.0 on 2022-01-02 14:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=230)),
                ('parentesco', models.CharField(blank=True, choices=[('C', 'Conjuge'), ('F', 'Filho / Enteado'), ('I', 'Irmao'), ('P', 'Pai / Mae'), ('S', 'Sogro / Sogra'), ('A', 'Avo / Bisavo'), ('N', 'Neto / Bisneto'), ('B', 'Bisneto'), ('In', 'Incapaz'), ('M', 'Outros menores')], default='F', max_length=3)),
                ('sexo', models.CharField(blank=True, choices=[('N', 'Nao Informado'), ('M', 'Masculino'), ('F', 'Feminino')], max_length=3)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('rg', models.CharField(blank=True, max_length=20)),
                ('rg_emissao', models.DateField(blank=True, null=True)),
                ('rg_orgao_expedidor', models.CharField(blank=True, max_length=15)),
                ('cpf', models.CharField(blank=True, max_length=20)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pessoal.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Afastamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(blank=True, choices=[('D', 'Doenca'), ('A', 'Acidente Trabalho'), ('O', 'Outro')], default='D', max_length=3)),
                ('data_afastamento', models.DateField(blank=True, default=datetime.datetime.today, null=True)),
                ('data_retorno', models.DateField(blank=True, null=True)),
                ('reabilitado', models.BooleanField(default=False)),
                ('detalhe', models.TextField(blank=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pessoal.funcionario')),
            ],
        ),
    ]
