# Generated by Django 4.0.2 on 2022-04-13 01:44

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=80)),
                ('tipo', models.CharField(choices=[('PR', 'Produtivo'), ('FO', 'Folga'), ('FE', 'Ferias'), ('FA', 'Falta')], default='PR', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalhe', models.CharField(blank=True, max_length=200)),
                ('validado', models.BooleanField(default=False)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pessoal.evento')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pessoal.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Apontamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EN', 'Entrada'), ('II', 'Inicio intervalo'), ('TI', 'Termino intervalo'), ('TR', 'Saida')], max_length=3)),
                ('data', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('info', models.CharField(blank=True, max_length=200)),
                ('geolocation', models.CharField(blank=True, max_length=230)),
                ('foto', core.models.ImageField(blank=True, upload_to='pessoal/frequencia/%Y/%m/%d')),
                ('frequencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoal.frequencia')),
            ],
        ),
    ]
